[project]
name = "cherryai-0621"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.28.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "langchain>=0.1.0",
    "langchain-core>=0.1.0",
    "langchain-community>=0.0.10",
    "langchain-openai>=0.0.5",
    "langchain-experimental>=0.0.47",
    "langgraph>=0.0.26",
    "langchain-ollama>=0.0.1",
    "scipy>=1.10.0",
    "scikit-learn>=1.3.0",
    "openpyxl>=3.1.0",
    "plotly>=5.17.0",
    "networkx>=3.1",
    "python-dotenv>=1.0.0",
    "pydantic>=2.0.0",
    "typing-extensions>=4.8.0",
    "nest-asyncio>=1.5.8",
    "aiohttp>=3.9.0",
    "pytest>=7.4.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "langfuse>=2.0.0,<3.0.0",
    # MCP server dependencies
    "fastmcp>=0.3.0",
    "mcp>=1.0.0",
    "uvicorn>=0.30.0",
    "langchain-mcp-adapters>=0.1.0",
    "xgboost>=2.0.0",
    "catboost>=1.2.0",
    "lightgbm>=4.0.0",
    "imbalanced-learn>=0.11.0",
    "statsmodels>=0.14.0",
    "pingouin>=0.5.0",
    "mlxtend>=0.23.0",
    "umap-learn>=0.5.0",
    "shap>=0.45.0",
    "lime>=0.2.0",
    "optuna>=3.5.0",
]

[project.optional-dependencies]
ml = [
    "tensorflow>=2.15.0",
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "transformers>=4.36.0",
    "datasets>=2.14.0",
]
monitoring = [
    "langsmith>=0.0.87",
    "wandb>=0.16.0",
]
