[project]
name = "cherryai-0621"
version = "0.1.0"
description = "AI-powered data analysis and visualization platform with LangChain, LangGraph, and MCP support"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # Core framework
    "streamlit>=1.46.0",
    # Data processing
    "pandas>=2.3.0",
    "numpy>=2.1.0",
    "openpyxl>=3.1.0",
    # Visualization
    "matplotlib>=3.10.0",
    "seaborn>=0.13.0",
    "plotly>=6.1.0",
    "networkx>=3.5",
    # LangChain ecosystem
    "langchain>=0.3.26",
    "langchain-core>=0.3.66",
    "langchain-community>=0.3.26",
    "langchain-openai>=0.3.24",
    "langchain-ollama>=0.3.3",
    "langgraph>=0.4.8",
    # Machine Learning
    "scikit-learn>=1.6.0",
    "xgboost>=3.0.0",
    "catboost>=1.2.8",
    "lightgbm>=4.6.0",
    # Statistical analysis
    "statsmodels>=0.14.4",
    # MCP server dependencies
    "fastmcp>=2.8.0",
    "mcp>=1.9.0",
    "uvicorn>=0.34.0",
    # Utilities
    "python-dotenv>=1.1.0",
    "pydantic>=2.11.0",
    "typing-extensions>=4.8.0",
    "nest-asyncio>=1.6.0",
    "aiohttp>=3.12.0",
    "psutil>=6.0.0",
    # Optional: Observability
    "langfuse>=2.60.0,<3.0.0",
    "ollama>=0.5.1",
    "langchain-experimental>=0.3.4",
    "langchain-mcp-adapters>=0.1.7",
    "python-a2a>=0.5.9",
    "fastapi>=0.115.13",
    "uvicorn>=0.30.1",
    "sqlalchemy>=2.0.31",
    "ydata-profiling>=4.7.0",
    "h2o>=3.46.0",
    "mlflow>=2.14.3",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-mock>=3.12.0",
    "pytest-asyncio>=0.23.0",
    "httpx>=0.27.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
]
advanced-ml = [
    "imbalanced-learn>=0.11.0",
    "pingouin>=0.5.0",
    "mlxtend>=0.23.0",
    "umap-learn>=0.5.0",
    "shap>=0.45.0",
    "lime>=0.2.0",
    "optuna>=3.5.0",
    "scikit-learn>=1.5.1",
    "ydata-profiling>=4.7.0",
    "plotly>=5.23.0",
]
monitoring = [
    "langsmith>=0.0.87",
    "wandb>=0.16.0",
]

[tool.poetry.group.dev.dependencies]
# ... existing code ...

[tool.setuptools.packages.find]
where = ["."]
include = ["core*", "ui*", "mcp_servers*"]
exclude = ["tests*"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
