global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rules for alerting
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Universal Engine metrics
  - job_name: 'universal-engine'
    static_configs:
      - targets: ['universal-engine:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # A2A Agents metrics
  - job_name: 'a2a-agents'
    static_configs:
      - targets: 
        - 'universal-engine:8306'  # Data Cleaner
        - 'universal-engine:8307'  # EDA Tools
        - 'universal-engine:8308'  # Statistical Analyzer
        - 'universal-engine:8309'  # Visualization
        - 'universal-engine:8310'  # ML Modeling
        - 'universal-engine:8311'  # Text Analytics
        - 'universal-engine:8312'  # Time Series
        - 'universal-engine:8313'  # Report Generator
        - 'universal-engine:8314'  # Data Validator
        - 'universal-engine:8315'  # Performance Monitor
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Ollama metrics
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # System metrics (Node Exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 15s