# Cherry AI Streamlit Platform - Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Cherry AI Main Application
  - job_name: 'cherry-ai-app'
    static_configs:
      - targets: ['cherry-ai-app:8501']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # A2A Agents
  - job_name: 'data-cleaning-agent'
    static_configs:
      - targets: ['data-cleaning-agent:8306']
    metrics_path: '/metrics'

  - job_name: 'data-loader-agent'
    static_configs:
      - targets: ['data-loader-agent:8307']
    metrics_path: '/metrics'

  - job_name: 'visualization-agent'
    static_configs:
      - targets: ['visualization-agent:8308']
    metrics_path: '/metrics'

  - job_name: 'wrangling-agent'
    static_configs:
      - targets: ['wrangling-agent:8309']
    metrics_path: '/metrics'

  - job_name: 'feature-engineering-agent'
    static_configs:
      - targets: ['feature-engineering-agent:8310']
    metrics_path: '/metrics'

  - job_name: 'sql-database-agent'
    static_configs:
      - targets: ['sql-database-agent:8311']
    metrics_path: '/metrics'

  - job_name: 'eda-tools-agent'
    static_configs:
      - targets: ['eda-tools-agent:8312']
    metrics_path: '/metrics'

  - job_name: 'h2o-ml-agent'
    static_configs:
      - targets: ['h2o-ml-agent:8313']
    metrics_path: '/metrics'

  - job_name: 'mlflow-tools-agent'
    static_configs:
      - targets: ['mlflow-tools-agent:8314']
    metrics_path: '/metrics'

  - job_name: 'pandas-hub-agent'
    static_configs:
      - targets: ['pandas-hub-agent:8315']
    metrics_path: '/metrics'

  # Infrastructure Services
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093