[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"

[global]
developmentMode = false
showWarningOnDirectExecution = false
suppressDeprecationWarnings = true

[server]
runOnSave = false
allowRunOnSave = false
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = true

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
